services:
  app:
    image: antuan555/docker-project:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8080"